name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Go to machines service contracts directory
      run: cd src/contracts/machines

    - name: Build machines service contracts
      run: go build -v ./...
    
    - name: Go to machines service directory
      run: cd ../../machines

    - name: Build machines service
      run: go build -v ./...

    - name: Test machines service
      run: go test -v ./...
